project:
  type: book
  output-dir: docs
  
book:
  title: "Global Families Project"
  author: "Global Families Project Team"
  date: "today"
  cover-image: positiveparenting-cover.png
  downloads: [pdf]
  twitter-card: true
  open-graph: true
  favicon: logo-globe.png
  site-url: https://agrogan1.github.io/globalfamilies
  search: true
  repo-url: https://github.com/agrogan1/globalfamilies
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - team.qmd
    - simulated-multi-country-data.qmd
    - quick-intro-R.qmd
    - quick-intro-ggplot2.qmd
    - quantitative-data-analysis.qmd
    - references.qmd
  appendices:
    - simulate-data.qmd
  navbar:
    background: "#1CABE2"
     
bibliography: globalfamilies.bib

csl: apa.csl

google-scholar: true

format:
  html:
    theme: 
      light: cosmo
      dark: vapor
    css: globalfamilies.css
    execute:
      freeze: auto
  pdf:
    documentclass: scrreprt
    lot: true
    lof: true

